/*const base = {
  'Digit1': 'a',
  'Digit2': 'b',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}

const shift = {
  'Digit1': 'A',
  'Digit2': 'B',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}

const caps = {
  'Digit1': '+',
  'Digit2': '-',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}
*/

const base = {
  "Backquote": "`",
  "Digit1": "1",
  "Digit2": "2",
  "Digit3": "3",
  "Digit4": "4",
  "Digit5": "5",
  "Digit6": "6",
  "Digit7": "7",
  "Digit8": "8",
  "Digit9": "9",
  "Digit0": "0",
  "Minus": "-",
  "Equal": "=",
  "Backspace": "",
  "Tab": "",
  "KeyQ": "q",
  "KeyW": "w",
  "KeyE": "e",
  "KeyR": "r",
  "KeyT": "t",
  "KeyY": "y",
  "KeyU": "u",
  "KeyI": "i",
  "KeyO": "o",
  "KeyP": "p",
  "BracketLeft": "[",
  "BracketRight": "]",
  "Backslash": "\\",
  "CapsLock": "",
  "KeyA": "a",
  "KeyS": "s",
  "KeyD": "d",
  "KeyF": "f",
  "KeyG": "g",
  "KeyH": "h",
  "KeyJ": "j",
  "KeyK": "k",
  "KeyL": "l",
  "Semicolon": ";",
  "Quote": "'",
  "Enter": "\n",
  "ShiftLeft": "",
  "KeyZ": "z",
  "KeyX": "x",
  "KeyC": "c",
  "KeyV": "v",
  "KeyB": "b",
  "KeyN": "n",
  "KeyM": "m",
  "Comma": ",",
  "Period": ".",
  "Slash": "/",
  "ArrowUp": "",
  "ShiftRight": "",
  "ControlLeft": "",
  "AltLeft": "",
  "Space": " ",
  "AltRight": "",
  "ControlRight": "",
  "ArrowLeft": "",
  "ArrowDown": "",
  "ArrowRight": "",
  "Lang": ""
};

const shift = {
  "Backquote": "~",
  "Digit1": "!",
  "Digit2": "@",
  "Digit3": "#",
  "Digit4": "$",
  "Digit5": "%",
  "Digit6": "^",
  "Digit7": "&",
  "Digit8": "*",
  "Digit9": "(",
  "Digit0": ")",
  "Minus": "_",
  "Equal": "+",
  "Backspace": "",
  "Tab": "",
  "KeyQ": "q",
  "KeyW": "w",
  "KeyE": "e",
  "KeyR": "r",
  "KeyT": "t",
  "KeyY": "y",
  "KeyU": "u",
  "KeyI": "i",
  "KeyO": "o",
  "KeyP": "p",
  "BracketLeft": "[",
  "BracketRight": "]",
  "Backslash": "\\",
  "CapsLock": "",
  "KeyA": "a",
  "KeyS": "s",
  "KeyD": "d",
  "KeyF": "f",
  "KeyG": "g",
  "KeyH": "h",
  "KeyJ": "j",
  "KeyK": "k",
  "KeyL": "l",
  "Semicolon": ";",
  "Quote": "'",
  "Enter": "\n",
  "ShiftLeft": "",
  "KeyZ": "z",
  "KeyX": "x",
  "KeyC": "c",
  "KeyV": "v",
  "KeyB": "b",
  "KeyN": "n",
  "KeyM": "m",
  "Comma": ",",
  "Period": ".",
  "Slash": "/",
  "ArrowUp": "",
  "ShiftRight": "",
  "ControlLeft": "",
  "AltLeft": "",
  "Space": " ",
  "AltRight": "",
  "ControlRight": "",
  "ArrowLeft": "",
  "ArrowDown": "",
  "ArrowRight": "",
  "Lang": ""
};

const caps = {
  "Backquote": "`",
  "Digit1": "1",
  "Digit2": "2",
  "Digit3": "3",
  "Digit4": "4",
  "Digit5": "5",
  "Digit6": "6",
  "Digit7": "7",
  "Digit8": "8",
  "Digit9": "9",
  "Digit0": "0",
  "Minus": "-",
  "Equal": "=",
  "Backspace": "",
  "Tab": "",
  "KeyQ": "q",
  "KeyW": "w",
  "KeyE": "e",
  "KeyR": "r",
  "KeyT": "t",
  "KeyY": "y",
  "KeyU": "u",
  "KeyI": "i",
  "KeyO": "o",
  "KeyP": "p",
  "BracketLeft": "[",
  "BracketRight": "]",
  "Backslash": "\\",
  "CapsLock": "",
  "KeyA": "a",
  "KeyS": "s",
  "KeyD": "d",
  "KeyF": "f",
  "KeyG": "g",
  "KeyH": "h",
  "KeyJ": "j",
  "KeyK": "k",
  "KeyL": "l",
  "Semicolon": ";",
  "Quote": "'",
  "Enter": "\n",
  "ShiftLeft": "",
  "KeyZ": "z",
  "KeyX": "x",
  "KeyC": "c",
  "KeyV": "v",
  "KeyB": "b",
  "KeyN": "n",
  "KeyM": "m",
  "Comma": ",",
  "Period": ".",
  "Slash": "/",
  "ArrowUp": "",
  "ShiftRight": "",
  "ControlLeft": "",
  "AltLeft": "",
  "Space": " ",
  "AltRight": "",
  "ControlRight": "",
  "ArrowLeft": "",
  "ArrowDown": "",
  "ArrowRight": "",
  "Lang": ""
};
export default {base, shift, caps};