const layoutTest = [
  [
    'Digit1',
    'Digit2',
    'Backspace',
    'ShiftLeft',
    'CapsLock',
    'Lang'
  ]
]

const layout = [
  [
    "Backquote",
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Digit7",
    "Digit8",
    "Digit9",
    "Digit0",
    "Minus",
    "Equal",
    "Backspace",
  ],
  [
    "Tab",
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "KeyU",
    "KeyI",
    "KeyO",
    "KeyP",
    "BracketLeft",
    "BracketRight",
    "Backslash",
  ],
  [
    "CapsLock",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyF",
    "KeyG",
    "KeyH",
    "KeyJ",
    "KeyK",
    "KeyL",
    "Semicolon",
    "Quote",
    "Enter",
  ],
  [
    "ShiftLeft",
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyV",
    "KeyB",
    "KeyN",
    "KeyM",
    "Comma",
    "Period",
    "Slash",
    "ArrowUp",
    "ShiftRight"
  ],
  [
    "ControlLeft",
    "AltLeft",
    "Space",
    "AltRight",
    "ControlRight",
    "ArrowLeft",
    "ArrowDown",
    "ArrowRight",
    "Lang",
  ]
];

export default layout;


export const en: Record<string, string> = {
    "Backquote": "`",
    "Digit1": "1",
    "Digit2": "2",
    "Digit3": "3",
    "Digit4": "4",
    "Digit5": "5",
    "Digit6": "6",
    "Digit7": "7",
    "Digit8": "8",
    "Digit9": "9",
    "Digit0": "0",
    "Minus": "-",
    "Equal": "=",
    "Backspace": "",
    "Tab": "",
    "KeyQ": "q",
    "KeyW": "w",
    "KeyE": "e",
    "KeyR": "r",
    "KeyT": "t",
    "KeyY": "y",
    "KeyU": "u",
    "KeyI": "i",
    "KeyO": "o",
    "KeyP": "p",
    "BracketLeft": "[",
    "BracketRight": "]",
    "Backslash": "\\",
    "CapsLock": "",
    "KeyA": "a",
    "KeyS": "s",
    "KeyD": "d",
    "KeyF": "f",
    "KeyG": "g",
    "KeyH": "h",
    "KeyJ": "j",
    "KeyK": "k",
    "KeyL": "l",
    "Semicolon": ";",
    "Quote": "'",
    "Enter": "\n",
    "ShiftLeft": "",
    "KeyZ": "z",
    "KeyX": "x",
    "KeyC": "c",
    "KeyV": "v",
    "KeyB": "b",
    "KeyN": "n",
    "KeyM": "m",
    "Comma": ",",
    "Period": ".",
    "Slash": "/",
    "ArrowUp": "",
    "ShiftRight": "",
    "ControlLeft": "",
    "AltLeft": "",
    "Space": " ",
    "AltRight": "",
    "ControlRight": "",
    "ArrowLeft": "",
    "ArrowDown": "",
    "ArrowRight": "",
    "Lang": ""
};

export const ru: Record<string, string> = {
  "Backquote": "ё",
  "Digit1": "1",
  "Digit2": "2",
  "Digit3": "3",
  "Digit4": "4",
  "Digit5": "5",
  "Digit6": "6",
  "Digit7": "7",
  "Digit8": "8",
  "Digit9": "9",
  "Digit0": "0",
  "Minus": "-",
  "Equal": "=",
  "Backspace": "",
  "Tab": "",
  "KeyQ": "й",
  "KeyW": "ц",
  "KeyE": "у",
  "KeyR": "к",
  "KeyT": "е",
  "KeyY": "н",
  "KeyU": "г",
  "KeyI": "ш",
  "KeyO": "щ",
  "KeyP": "з",
  "BracketLeft": "х",
  "BracketRight": "ъ",
  "Backslash": "\\",
  "CapsLock": "",
  "KeyA": "ф",
  "KeyS": "ы",
  "KeyD": "в",
  "KeyF": "а",
  "KeyG": "п",
  "KeyH": "р",
  "KeyJ": "о",
  "KeyK": "л",
  "KeyL": "д",
  "Semicolon": "ж",
  "Quote": "э",
  "Enter": "\n",
  "ShiftLeft": "",
  "KeyZ": "я",
  "KeyX": "ч",
  "KeyC": "с",
  "KeyV": "м",
  "KeyB": "и",
  "KeyN": "т",
  "KeyM": "ь",
  "Comma": "б",
  "Period": "ю",
  "Slash": ".",
  "ArrowUp": "",
  "ShiftRight": "",
  "ControlLeft": "",
  "AltLeft": "",
  "Space": " ",
  "AltRight": "",
  "ControlRight": "",
  "ArrowLeft": "",
  "ArrowDown": "",
  "ArrowRight": "",
  "Lang": ""
};
