/*const base = {
  'Digit1': '1',
  'Digit2': '2',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}

const shift = {
  'Digit1': '10',
  'Digit2': '20',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}

const caps = {
  'Digit1': '!',
  'Digit2': '@',
  'Backspace': 'Backspace',
  'ShiftLeft': 'Shift',
  'CapsLock': 'Caps',
  'Lang': 'Lang'
}*/

export const base = {
  "Backquote": "ё",
  "Digit1": "1",
  "Digit2": "2",
  "Digit3": "3",
  "Digit4": "4",
  "Digit5": "5",
  "Digit6": "6",
  "Digit7": "7",
  "Digit8": "8",
  "Digit9": "9",
  "Digit0": "0",
  "Minus": "-",
  "Equal": "=",
  "Backspace": "",
  "Tab": "",
  "KeyQ": "й",
  "KeyW": "ц",
  "KeyE": "у",
  "KeyR": "к",
  "KeyT": "е",
  "KeyY": "н",
  "KeyU": "г",
  "KeyI": "ш",
  "KeyO": "щ",
  "KeyP": "з",
  "BracketLeft": "х",
  "BracketRight": "ъ",
  "Backslash": "\\",
  "CapsLock": "",
  "KeyA": "ф",
  "KeyS": "ы",
  "KeyD": "в",
  "KeyF": "а",
  "KeyG": "п",
  "KeyH": "р",
  "KeyJ": "о",
  "KeyK": "л",
  "KeyL": "д",
  "Semicolon": "ж",
  "Quote": "э",
  "Enter": "\n",
  "ShiftLeft": "",
  "KeyZ": "я",
  "KeyX": "ч",
  "KeyC": "с",
  "KeyV": "м",
  "KeyB": "и",
  "KeyN": "т",
  "KeyM": "ь",
  "Comma": "б",
  "Period": "ю",
  "Slash": ".",
  "ArrowUp": "",
  "ShiftRight": "",
  "ControlLeft": "",
  "AltLeft": "",
  "Space": " ",
  "AltRight": "",
  "ControlRight": "",
  "ArrowLeft": "",
  "ArrowDown": "",
  "ArrowRight": "",
  "Lang": ""
};


export default {base, shift:base, caps:base}//shift, caps};